# 服务端口
server:
#  ip: 47.99.172.18
  ip: 192.168.1.25
  port: 8001

spring:
  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.99.172.18:3306/itoutiao?serverTimezone=GMT%2B8
    url: jdbc:mysql://192.168.1.25:3306/itoutiao?serverTimezone=GMT%2B8
    username: root
    password: 123456

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置日志级别
logging:
  level:
    root: info

#文件存放的位置
file:
  path: /home/filePath/
#  path: E:\filePath\
